### ISSUE TITLE
Shift-Extruding a face on perpindicular axis, with "Intersect..." on, results in bad geometry

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#134]
1. new cube
1. face mode > select any face
1. ensure "Intersect Parallel" is turned On
1. shift-extrude on any axis perpindicular to the face normal

Result:
![image](https://cloud.githubusercontent.com/assets/5855470/22313330/7a2e3310-e32a-11e6-811d-43d470e6b622.png)

**Comment by arthursw** [comment]
This is a kind of normal behavior: ProBuilder removes faces in order to keep a maximum of 2 faces per edge. 

Here, one face was deleted because its right edge had three faces.

This prevents faces being created inside the mesh when using the auto-intersection algorithm, as it sometimes happens in sketchup.

It took me a looong time to find a algorithm for this task. I tried very complex methods, to try to guess which face to keep, but it turns out that this simple behaviour is better than what I tried. It could probably be improved, I'm not sure how yet, maybe we can open an improvement request for this in middle / long term milestone?

What did you want to create by extruding a face on its side?

**Comment by gabrielw-us** [comment]
I think we should always do one of 2 options:

1) Apply a fix to the geometry, but only if it results in something that feels like "oh, this is what would happen in the real world". This is always the best option, but not always possible.

or,

2) Do no special actions, just "follow orders". This might result in bad geo, but it doesn't confuse the user by doing actions they did not ask for.

In this case, item 1 is not possible -there is no "real world" result for sliding that face over. So, I say we just leave the geometry alone, don't attempt to apply any fixes. There will be zero-area faces, and overlapping edges, but the user can learn from this.

As an alternate example, in #128 , we can and definitely should use item 1- if I pulled two adjacent corners of a table together, it would form a wooden triangle. This requires hidden background actions (merging those verts and replacing the quad with a tri), but the user expects this.

Does that make okay sense? I've been thinking a LOT about these two "Methods", and might even make a video/post talking about it, and share that out. I think it's something that goes the wrong way too often.

**Comment by arthursw** [comment]
I agree, but here we are precisely in the second case : "Intersects with faces" is checked.
If the user wants bad geometry, he should uncheck that. 

That said, the algorithm to prevent unwanted faces can probably be improved.

**Comment by gabrielw-us** [comment]
Ah, I'm sorry, I keep mis-interpreting that. Yes, you are 100% correct. I think there might be a way to make this more clear in the GUI, I'll think on it.

**Comment by arthursw** [comment]
Ok, I improved many things, all this should be clearer now.
