### ISSUE TITLE
Vertices go "Off the Grid" after scaling, unable to get back on grid

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#152]
I'm not sure how the grid system actually works in PB-Unreal, or if this is Unreal doing grid work? I'd like to chat on that separately, actually.

Anyway, I've noticed if you scale an edge, it appears to "snap" to something (the scaling isn't smooth/freeform, it jumps to positions). So, I assume that's grid snapping, on purpose? However, the vertices are not aligned to the grid afterward, and if you try to re-align them, one-by-one, you can't- they are stuck "off grid".

**Comment by arthursw** [comment]
In UE you have a snap scale option, the last button in the following image :

<img width="332" alt="capture d ecran 2017-01-30 a 14 35 06" src="https://cloud.githubusercontent.com/assets/1814799/22425002/61206ed8-e6f9-11e6-8cff-7d38febe8026.png">

That said, when we have the advance snap options we could choose if the snap applies relatively to the current position (as it is right now) or if it forces moving the vertices on the grid.

I think forcing the vertices on the grid is a good thing, but only if user is aware it will do it, and probably only in vertex mode. Imaging a face rotated so that it's not aligned to the grid, it would be deformed if each of its vertices would be snapped on the grid.

From what I tried on my version of ProBuilder unity, it has the same behaviour as ProBuilder for Unreal : in edit > Snap Settings, I set the snap to 1 in all directions, I create a cube, select a face and scale/rotate it so that it's not on the grid, select one vertex and try to set it back on the grid : it does not. Maybe I have an old version of PB 4 Unity and you changed this behaviour. If so, what did you do exactly?

For now I'll create a button in vertex mode : move selected vertices on grid. It will move to the closest grid point. I can also make a special key trigger that function when the user is moving vertices in vertex mode.

This is not a trivial spec, so tell me if you have something better in mind (I didn't think a lot about it).

**Comment by arthursw** [comment]
Move vertex on grid button: Done!

**Comment by arthursw** [comment]
Shortcut to move vertices on grid (in vertex mode): Done!

**Comment by gabrielw-us** [comment]
Ah, ok- that sounds right.

Currently in PB-Unity:
- if you scale or rotate, the grid is totally ignored
- if you scale or rotate while holding CTRL, the grid is still ignored, but the action is done by "amounts" - ie, rotate 15 degrees, or scale .25x
- if you move vertices/faces/edges, all affected verts will snap to the grid
- there is a special "Push To Grid" button, which will take all selected vertices and move them to the nearest grid position for each

I 100% agree, we should not snap to grid when rotating or scaling. Only when moving.

The problem I see in Unreal is, once the vertex goes "off the grid", it doesn't go back "on grid". Like in the example up top, after scaling some verts, they are off the grid. That's fine! But, when I use "Move" on the vertex, it should go back to the grid.

Hopefully that's more clear :)

**Comment by arthursw** [comment]
> if you move vertices/faces/edges, all affected verts will snap to the grid

It's not what I've seen (but maybe I have a different version or I did something wrong), if your vertices are off-the-grid because of a face rotation, moving the face won't snap vertices on the gris (which is a good thing because it could potentially break the face coplanarity).

So I believe (but correct me if I am wrong) the behaviour in Unity and UE are the same, now (I just added the 'ctrl' shortcut key which snaps vertices on the grid while transforming, if needed).

**Comment by gabrielw-us** [comment]
I'll re-test when there is a new version, and we can do a live vid chat if needed. Tricky subject to explain without live demo :)

**Comment by arthursw** [comment]
Ok, this should be fine, I close now, feel free to double check ;)

**Comment by gabrielw-us** [comment]
Looks like this is still an issue, here's a simple repro:

1) New cube
2) Scale the bottom face outward
3) Notice the verts are no longer on the grid
4) Select any one of the verts that are now off the grid
5) Move that vert- it moves by snap amounts, but does not snap to the grid anymore

![image](https://cloud.githubusercontent.com/assets/5855470/23517762/4cdf769a-ff3f-11e6-8ba4-568c09d39b46.png)

**Comment by arthursw** [comment]
* from what I've tried. Show me if I'm wrong, maybe I tested on an old version.

**Comment by arthursw** [comment]
There is a shortcut to move vertices on the grid while transforming, I think it's Control but I'll have to check this.

**Comment by arthursw** [comment]
There is also a button to do it.

**Comment by gabrielw-us** [comment]
Okay, I'm asking Joe about this because I swear it can't be right, Unreal seems to have just as bad snapping as Unity (slightly better...). More on that later.

Anyway: clearing things up 100% here, hopefully:

PB in Unity: if I scale verts, zero snapping occurs.
PB in Unreal: if I scale verts, the verts move by exact amounts, but do not snap to grid

I think it's important to stick with "All or Nothing". Either the verts do zero snapping (PB Unity style), or they snap to actual grid points, not just moving by grid increments. The problem is, if the verts _look_ like they are snapping, but are actually just moving by increment, geometry gets confused and ugly real quick. Verts  you thought were on the grid, are suddenly not lining up, there are gaps and holes, etc.

So, I would prefer they either do zero snapping, or fully snap to actual grid points. The same for moving and rotating vertices, actually.

The problem is, Unreal's grid snapping is driving me crazy. It doesn't actually work as grid snapping should...ok, I'm closing this topic, creating a new, cleaner topic now that I understand the full issue. I promise that new topic/ticket will make better sense :)

**Comment by arthursw** [comment]
Again:

In UE you have a snap scale option, the last button in the following image :

<img width="332" alt="capture d ecran 2017-01-30 a 14 35 06" src="https://cloud.githubusercontent.com/assets/1814799/22425002/61206ed8-e6f9-11e6-8cff-7d38febe8026.png">


That is why the scale is snapped in Unreal Engine. Since scaling is a multiply operation, it can only snap by "multiply amount".

**Comment by gabrielw-us** [comment]
Yep, I understand all this now, new issue created that properly talks about the issue and offers solutions here: #206
