### ISSUE TITLE
When creating box shape, moving mouse far to left/right can disrupt height

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#196]
Using the v5 Project and Unreal 4.14.3

1. Enter "Create Shape" mode
1. Draw the base of a box
1. Now, move mouse far to left or right
1. Attempt to set box height- is difficult or sometimes impossible to get correct

Moving the mouse so far probably won't happen often, but even small amounts left/right seem to affect the height setting.

Could the height creation be limited to only up/down movement of the mouse, and just ignore sideways movement?

![box-draw](https://cloud.githubusercontent.com/assets/5855470/23080072/7b430e10-f51d-11e6-8e2f-d737bd8a4072.gif)

**Comment by arthursw** [comment]
This is a bit complicated:
 - when creating a box, the base rectangle is defined by the two first clicks projected on the ground,
 - the height is then computed from the vertical distance between the last click and the projection of the new mouse position on a vertical plane,
 - this vertical plane depends on the camera direction.

Since the two first points are defined in world space, the third must also be defined in world space ; this means we cannot use screen space coordinates for the height (= the amount of pixels the mouse was dragged vertically). Using screen space would require "magic conversion" from screen space to world space (10 pixel = how many world units ??).

This is also more robust to strange camera angles where "the sky is not upward" (although I don't know if it can happen outside the orthogonal views). More important, when we will add the feature to create a box on an existing face, the height won't be necessarily upward.

I added a grid helper to explain where the mouse point is projected on the vertical plane, and how the resulting height is computed. I think it's pretty self-explanatory, but there is probably room for improvement.

**Comment by gabrielw-us** [comment]
Okay, cool, that makes sense. Thanks for the detail!

**Comment by arthursw** [comment]
Just to illustrate how it works now:

![extrudegridguid](https://cloud.githubusercontent.com/assets/1814799/23271483/d5be53ca-f9f7-11e6-999a-d897b8e0fd25.gif)

**Comment by gabrielw-us** [comment]
Neat! I worry the grid might confuse people (it looks like a mesh preview/something)... could you try showing just the top line (from mouse pointer to top of box) ?

**Comment by arthursw** [comment]
Yes, I thought about that, I was still unsure which is the best solution. Now that you say it, I think just a line is enough. It could be the top line, as you say, or the vertical line under the cursor. Maybe I will create a checkbox to choose between the two, just for us to choose the best option.
