### ISSUE TITLE
After using "Edit > Duplicate" on a shape, elements can not be edited

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#22]
1. Draw PB cube
1. Switch to Select/Transform mode, Object level, select PB cube
1. Using top menu, click "Edit > Duplicate"
1. Select the new PB cube, move apart from old
1. Attempt to edit elements on the new cube- unable to select any.

**Comment by arthursw** [comment]
Wow! This is not surprise but I don't know how I'll solve this quickly. It might be fairly simple, but I'm not sure.

A quick fix would be to have a "Duplicate" button in ProBuilder interface, so that I can properly duplicate the object along with the ProBuilder data. Maybe we can have a symmetry tool as well.

**Comment by gabrielw-us** [comment]
From our experience in PB-Unity, going the quick-fix route will not help. We did that for a few things, and it generated a LOT of backlash.

It'll be a tough issue to fix, but important. Especially something as basic as duplicate, people will expect that to work everytime, and never see the special button we create- or if they do, they'll still be unhappy.

**Comment by arthursw** [comment]
I'll see what I can do.

**Comment by arthursw** [comment]
Ok, it took me a while to find how to solve this problem but it's almost fixed.

**Comment by gabrielw-us** [comment]
Awesome

**Comment by arthursw** [comment]
fixed
