### ISSUE TITLE
"Convert static mesh" should read "Convert to Static Mesh"

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#29]
Minor, but important :)

**Comment by arthursw** [comment]
Yes, very important, thank you ; I didn't take the time to properly name all the import/export button. It is problematic because we would need long names like "ProBuilder Mesh" and "Unreal Engine Static Mesh", "Unreal Engine Brush".

Do we need to precise "_selected_ objects"?

If you have good ideas for all the buttons tell me :-)

**Comment by gabrielw-us** [comment]
Yeah, this little stuff is always a pain, but important to catch :) I'll dig through and make cases for anything I see that needs fixing.

I think "PB Mesh" or "PB Object" is fine, people get the idea there :)
