### ISSUE TITLE
Offset creates incorrect geometry

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#43]
1. Select face
1. Click Offset, set a Positive value

The result is "impossible" geometry, with edges extruded from faces (see image below)

I'm not sure what the purpose of this function is, but this seems a strange result. Can you clarify?

![image](https://cloud.githubusercontent.com/assets/5855470/21295682/87e9034c-c528-11e6-9983-23acd83765ac.png)

**Comment by gabrielw-us** [comment]
Looks like Offset to negative value does what I call an "Inset", which is good. 

I think it should be doing something like this, right?

![inset](https://cloud.githubusercontent.com/assets/5855470/21295769/1b6a6952-c52a-11e6-9d31-09e3beb7c282.gif)

**Comment by arthursw** [comment]
Offset means inflating/deflating a polygon (inflating with positive values, deflating with negative values).

ProBuilder use the auto-intersection algorithm to create new faces from the newly created edges. The new faces should point in the same direction as the previously existing faces. That means when offsetting the top face of a cube, there will be a single face pointing upward (and no back face). This makes sens to me.

I have to make offset work without the auto-intersection algorithm.

You can do what you show in the video with the extrude tool, by pressing the shift key while dragging the scale tool (with a face selected).

I would not recommend creating a slider in the GUI to "extrude with the scale tool" since it often results in invalid shapes (as soon as you offset a concave polygon). In addition, the scale tool decrease/increase the size of selected object in percentage (2 times bigger), this makes it hard to have unit based values.

**Comment by arthursw** [comment]
I close this for now, please re-open if necessary.
