### ISSUE TITLE
Can you clarify "Merge Edges" and "Intersect Edges"?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#57]

**Comment by gabrielw-us** [comment]
Not sure what these are supposed to do, and can't get them to do anything currently.

**Comment by arthursw** [comment]
Ok both features had bugs that I fixed ;-)

"Merge edges" is used to merge collinear edges :
 - subdivide a face,
 - delete the 4 inner edges,
 - select two collinear edges (on the side) and click "Merge edges" to get only one edge ( and remove the middle vertex)

I renamed the "Merge edges" button to "Merge collinear edges".

"Intersect edges" is used to compute the intersection between edges which cross each other but which do not share any vertex. If the AutoIntersection plugin is on, it also recompute the faces to create valid faces.
To test : 
 - create a rectangle
 - select one vertex and move it so that two edges intersect
 - select both intersecting edges (they do not share any vertex) and click "Intersect edges" to create the new vertex at intersection (and compute new faces if AutoIntersection is on).

I didn't find a better name for this button, but tell me if you have an idea :-)
