### ISSUE TITLE
When adjacent faces are extruded with "As Group" off, do not weld vertices

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#64]
Currently, if I do an extrude with "As Group" turned off, and the faces are adjacent, they get welded up. This ends up "grouping" them and creating nasty geo.

Instead, I think the new result geometry should look like this, if pulled apart:
![image](https://cloud.githubusercontent.com/assets/5855470/21529903/c9f06bec-cd0a-11e6-86f5-3ab9182747d6.png)

**Comment by arthursw** [comment]
This is normal if you have "Intersect with parallel faces" checked. 
This option intersects all new faces with existing faces. 

Uncheck the checkbox and your problem is solved.
A warning message explains that one face has been created within the object.

Maybe it's better to never create face inside the object during extrude.

**Comment by gabrielw-us** [comment]
Yep, that's my thought- that extra face should not be created inside the object.
Is there any reason to keep the extra face?

**Comment by arthursw** [comment]
Ok now I delete the internal faces. The faces were created because it was the expected behaviour: extrude faces and intersect resulting colliding faces.

**Comment by gabrielw-us** [comment]
Hmm, yep, I think this is a good time for "hand holding", secretly fixing things for the user. Normally I'm against that, but they just won't expect those faces, since I can't imagine any situation where they would want them. Thanks!
