### ISSUE TITLE
Support for the 2D views

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#71]
I think it's important to support 2D views. Currently the whole interface screws up in various ways if I attempt to, say, move a face in a 2D view.

**Comment by gabrielw-us** [comment]
Ah, thanks, I hadn't tested this yet. 2D views are essential.

**Comment by joewintergreen** [comment]
Good to hear you reckon so! :D

**Comment by gabrielw-us** [comment]
Only madmen* do 3D without those views. (or grids, for that matter...)

_*unity_

**Comment by joewintergreen** [comment]
Agreed! Unity is so whack, man.

Here are some helpful gifs from that gold standard in 2D map editing, Hammer:

[marquee brush creation inferring Z height!](http://impromptugames.com/ue4/unitydoc/unitygif/hammer_createroom.gif)
[rotating/skewing etc with no widget!](http://impromptugames.com/ue4/unitydoc/unitygif/hammerstretchskewrotate.gif)

**Comment by arthursw** [comment]
Ok, this issue was split in three: [Transform box](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/88) and [snap height to face under cursor](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/104) and [Transform selection without gizmo](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/106). I close it for now, please re-open if necessary.
