### ISSUE TITLE
Applying materials to faces?

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#73]
I don't seem to be able to apply a material to a face, just the whole object. I also saw that in the face settings, there was a Texture reference (the default grid texture), which struck me as weird - surely you'll be texturing geo with materials, not textures? (Changing that reference didn't do anything either)

**Comment by gabrielw-us** [comment]
Oops- I forgot to mention, the material and UV stuff is still very much untested (by myself, at least). I've been focusing on modeling stuff for this release. @arthursw might have more info, but I think we might even leave that out for the next public Alpha, since it's a practically another tool all to itself.

**Comment by joewintergreen** [comment]
It is pretty janky still, but I'd at least let us drag a material onto a face for the next release - because even in the janky state they're in, they're maybe twenty, thirty times better than anything UE4's CSG tools are offering.

**Comment by joewintergreen** [comment]
-Tweaking UV dimensions/coordinates/justification using text boxes is often suboptimal, so definitely keep it up with the 3d-view approach to that, but also make sure your UI for it is at least as featureful as [Hammer's](http://impromptugames.com/ue4/unitydoc/unitygif/hammerfaceedit.gif)

-You need auto-stitch - Probuilder on Unity has this, but it's not as responsive as [Hammer's](http://impromptugames.com/ue4/unitydoc/unitygif/hammeruvarch2.gif)

**Comment by arthursw** [comment]
Ok, here is how it works for now:
 - select some faces,
 - set "Mesh group" to 1 (or any value),
 - go to object mode (keep the mesh selected),
 - select the Mesh Component in the right details panel,
 - you can set materials in the available slot (well, this is greyed out in your version, but I changed this)

We should probably improve this later on.

**Comment by joewintergreen** [comment]
I'd go so far as to say it should be improved as a matter of urgency :p

**Comment by arthursw** [comment]
Ok

Note that it seems incredibly slow to texture faces one-by-one in Hammer... But maybe there's a better way?

**Comment by joewintergreen** [comment]
It's really fast using a couple of shortcuts. I'll go into more detail when
I'm out of bed but mostly alt-right-click.

**Comment by arthursw** [comment]
You generally don't want to alt-right-click on a set of faces, especially when there're all aligned, this doesn't make sens, it seems like a computer task ; so if we improve this feature let's make it a nice one! (but maybe not right now..)

**Comment by joewintergreen** [comment]
Must be a misunderstanding going on here. I'll make a video a bit later
showing what I mean.

**Comment by arthursw** [comment]
Yes sorry I'm just guessing, waiting for you video

**Comment by joewintergreen** [comment]
[Here we go](http://impromptugames.com/impromptugames.com/ue4/sharex/hammerexample.mp4)

**Comment by arthursw** [comment]
Hm, I can't access the video...

**Comment by arthursw** [comment]
Oh yes I got it.

**Comment by arthursw** [comment]
Ok, auto-stitch is already implemented: select a face and middle mouse button (wheel click) on an adjacent face:

![janv -05-2017 11-35-33](https://cloud.githubusercontent.com/assets/1814799/21677589/1b096b2e-d33b-11e6-8cf2-15fc4f684934.gif)


I think we can make a tool which automatically apply auto-stich on a set of faces, instead of having to click on each single face. This could be initiated with an edge selected, just like the "select-loop" and "select-ring" features: "apply auto-stitch on the faces following this loop/ring". And it could be initiated with a set of selected faces, the auto-stitch could be initialized with the first face selected (you would have to select the first face with a click, and then you can select others with a selection rectangle).

**Comment by joewintergreen** [comment]
Cool, didn't realise that was in!
Anywhere I can go to get the most up to date build?

**Comment by arthursw** [comment]
I prefer fixing more bugs before releasing it...
I'll try to make a release next week.

**Comment by gabrielw-us** [comment]
I'd like to add, for the upcoming public release (still Alpha), we should probably just remove all UV and Material stuff.

Get the shape creation and geo editing really, super-duper good.

Then we can make texturing the sole focus of the next release.

**Comment by arthursw** [comment]
Ok all the issues in this thread have been created or fixed. I close it for now, feel free to re-open it if you think I forgot something.
